# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39dc12ce61dd39a7d88f3bdb2027817f13542523fd14af22d706c54be09c7d7aff396f19f75b5102fb71c7b983327b630cc3d6381173dcf52fbabf084397c288

test:
  secret_key_base: 8486e4ae5e64ae796fb072d529f35bfa776a486224eff3f3aa3deb02fa9d3f6bff00891bb86567bb77a10120f3378702a3aa60e59514078875dd470a9ab1500c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
